306 improved result parsing
hpc/pavilion2 pull request #311
Opened 2020-08-24 17:01 UTC by Paul-Ferrell

2020-08-24 19:13 UTC, Paul-Ferrell commented
Fixes #306

2020-08-24 19:14 UTC, Paul-Ferrell commented
Closes #306

2020-10-23 22:17 UTC, nicholas-sly requested changes
Looked over the documentation section.  Let me know if you have any questions.

2020-10-23 22:17 UTC, nicholas-sly commented on docs/tutorials/extracting_results.rst
> +Wild Evaluations
Is this supposed to be 'Wildcard Evaluations'?

2020-10-23 22:17 UTC, nicholas-sly commented on docs/tutorials/extracting_results.rst
> +variable, or
You wandered off again...

2020-10-26 15:29 UTC, Paul-Ferrell commented on docs/results/basics.rst
> +     }
If this were python, yes. But it's JSON, and a trailing comma is a syntax error.

2020-10-26 15:30 UTC, Paul-Ferrell commented on docs/results/evaluate.rst
> +            "test_node_list": ["node1", "node2", "node3"],
and other things.

2020-10-26 15:31 UTC, Paul-Ferrell commented on docs/results/evaluate.rst
> +            # Which will evaluate to ``4``.
:+1:

2020-10-26 15:38 UTC, Paul-Ferrell commented on docs/results/parse.rst
> +            "
For reminding me that I needed another example there, apparently.

2020-10-26 15:48 UTC, Paul-Ferrell commented on docs/results/parse.rst
> +- When using the **fullname** *per\_file* setting, the key cannot be
Yep, legacy naming. Fixed it.

2020-10-26 15:51 UTC, Paul-Ferrell commented on docs/tutorials/extracting_results.rst
> +There's a lot to parse here.
Worth it.

2020-10-26 15:52 UTC, Paul-Ferrell commented on docs/tutorials/extracting_results.rst
> +            pflops: 'gflops/1000'
:facepalm:

2020-10-26 18:27 UTC, francinelapid requested changes

2020-10-26 18:29 UTC, francinelapid commented
Forgot to add this to my review:
- looked through code 
- updated result parser tests look better

2020-10-27 11:31 UTC, merged