Run repeat
hpc/pavilion2 pull request #389
Opened 2021-02-19 22:32 UTC by kjeverson

closes issue #165 

Introduces a `--repeat` flag and also supports a `*` notation to repeat tests.

2021-02-23 16:38 UTC, Paul-Ferrell requested changes

2021-02-23 16:38 UTC, Paul-Ferrell commented on lib/pavilion/plugins/commands/run.py
> +                tests.append(test_name)
Make this work in both direction.  
 - 5*test
 - test*5

2021-02-23 16:38 UTC, Paul-Ferrell commented on lib/pavilion/plugins/commands/run.py
> +                tests.append(test_name)
You can drop the re entirely. 
Just check that '*' in test_name, and then do a single split(test_name, '*', 1).

2021-02-23 16:38 UTC, Paul-Ferrell commented on lib/pavilion/plugins/commands/run.py
> +                tests.append(test_name)
You also need to add this to the command argument documentation.

2021-02-23 23:16 UTC, kjeverson commented
Still need to drop `<suite_name>.*` support

2021-03-08 17:12 UTC, Paul-Ferrell approved these changes

2021-03-08 17:13 UTC, Paul-Ferrell approved these changes

2021-03-15 17:45 UTC, merged