Added -f and --follow option to pav log command.
hpc/pavilion2 pull request #570
Opened 2022-10-25 16:10 UTC by smehta99

Usage:  `pav log -f/--follow <log_type> <test_id>`

example: `pav log -f build 72`

2022-11-22 17:48 UTC, smehta99 commented
There is a bug where where build hash log doesn't change from the previous run and ends up not finding the new hash. I will fix it when I return.

2022-12-07 23:23 UTC, Paul-Ferrell requested changes

2022-12-07 23:23 UTC, Paul-Ferrell commented on lib/pavilion/commands/log.py
> +                                output.fprint(self.outfile, data, end='', flush=True)
Instead of jumping through all these possibilities, use a list of possible filename and just check each of them in turn.

2023-01-11 17:43 UTC, Paul-Ferrell requested changes

2023-01-11 17:43 UTC, Paul-Ferrell commented on lib/pavilion/commands/log.py
> +    def print_log(self, current_position, file):
Add docstring

2023-01-11 17:43 UTC, Paul-Ferrell commented on lib/pavilion/commands/log.py
> +    def print_log(self, current_position, file):
and arg types

2023-02-07 22:41 UTC, Paul-Ferrell approved these changes

2023-02-07 22:41 UTC, Paul-Ferrell commented on lib/pavilion/commands/log.py
> +                            with build_log_path.open() as file:
Race condition

2023-04-10 22:21 UTC, Paul-Ferrell commented on lib/pavilion/commands/log.py
> +                                elif args.follow:
These shouldn't be mutually exclusive. What if I want to tail and follow?

2023-08-14 18:19 UTC, merged